<a href="https://colab.research.google.com/github/bilgekagansenol/SpamornotSpamproject/blob/main/spamornotspam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import nltk
nltk.download('punkt',force=True)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:

import pandas as pd
import os

file_path = r"/content/drive/MyDrive/spamornotspamproject/emails/emails.csv"
if os.path.isfile(file_path):
    print("folder is found")
else:
    print("path is wrong or folder is not exist")

folder is found

In [4]:
df = pd.read_csv(file_path)
df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [5]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [6]:
df['tokenized_text'] = df['text'].apply(nltk.word_tokenize)

In [7]:
df.head()

,text,spam,tokenized_text
0,Subject: naturally irresistible your corporate...,1,"[Subject, :, naturally, irresistible, your, co..."
1,Subject: the stock trading gunslinger fanny i...,1,"[Subject, :, the, stock, trading, gunslinger, ..."
2,Subject: unbelievable new homes made easy im ...,1,"[Subject, :, unbelievable, new, homes, made, e..."
3,Subject: 4 color printing special request add...,1,"[Subject, :, 4, color, printing, special, requ..."
4,"Subject: do not have money , get software cds ...",1,"[Subject, :, do, not, have, money, ,, get, sof..."

In [8]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [9]:
import os
!git clone https://github.com/bilgekagansenol/SpamornotSpamproject

os.chdir('/content/SpamornotSpamproject')

Cloning into 'SpamornotSpamproject'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 46 (delta 21), reused 7 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (46/46), 234.81 KiB | 877.00 KiB/s, done.
Resolving deltas: 100% (21/21), done.

In [10]:
!ls

functions_cleaning_tokens.py  functions.ipynb  spamornotspam.ipynb

In [11]:
import functions_cleaning_tokens

df['tokenized_text'] = df['tokenized_text'].apply(functions_cleaning_tokens.clean_tokens)
df.head()

,text,spam,tokenized_text
0,Subject: naturally irresistible your corporate...,1,"[subject, naturally, irresistible, your, corpo..."
1,Subject: the stock trading gunslinger fanny i...,1,"[subject, the, stock, trading, gunslinger, fan..."
2,Subject: unbelievable new homes made easy im ...,1,"[subject, unbelievable, new, homes, made, easy..."
3,Subject: 4 color printing special request add...,1,"[subject, color, printing, special, request, a..."
4,"Subject: do not have money , get software cds ...",1,"[subject, do, not, have, money, get, software,..."

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [12]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [13]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [18]:
import pandas as pd
from nltk.corpus import stopwords
import nltk


nltk.download('stopwords')

stopwords1 = stopwords.words('english')
print(stopwords1)
list_of_tokens  = []
list_of_tokens = df['tokenized_text'].tolist()
cleaned_samples = [sample[1:] if sample and sample[0].lower() == 'subject' else sample for sample in list_of_tokens]
list_of_tokens = cleaned_samples
list_of_tokens = [token for token in list_of_tokens if token not in stopwords1 ]
df['tokenized_text'] = list_of_tokens
df.head()

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,text,spam,tokenized_text
0,Subject: naturally irresistible your corporate...,1,"[naturally, irresistible, your, corporate, ide..."
1,Subject: the stock trading gunslinger fanny i...,1,"[the, stock, trading, gunslinger, fanny, is, m..."
2,Subject: unbelievable new homes made easy im ...,1,"[unbelievable, new, homes, made, easy, im, wan..."
3,Subject: 4 color printing special request add...,1,"[color, printing, special, request, additional..."
4,"Subject: do not have money , get software cds ...",1,"[do, not, have, money, get, software, cds, fro..."

In [ ]:
from gensim.models import Word2Vec

In [ ]:

import pandas as pd
mails = df['tokenized_text'].tolist()
model1 = Word2Vec(sentences=mails, vector_size=100, window=5, min_count=1, workers=4)
model2 = Word2Vec(sentences=mails, vector_size=100, window=5, min_count=2, workers=4)
model5= wor
model.save("word2vec.model")